export const quietCtaPrimaryClass =
  "inline-flex min-h-[40px] max-w-full items-center justify-center gap-1.5 rounded-full border border-transparent bg-transparent px-3 py-2 text-center font-body text-[10px] uppercase tracking-[0.18em] text-primary transition-all duration-300 ease-out shadow-[inset_0_-1px_0_hsl(var(--primary)/0.22)] hover:border-primary/18 hover:bg-background/32 hover:shadow-[0_8px_16px_hsl(var(--background)/0.14)] focus-visible:border-primary/28 focus-visible:bg-background/44 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/35 active:border-primary/22 active:bg-background/40 sm:min-h-[42px] sm:px-3.5 sm:text-[11px] sm:tracking-[0.22em]";

export const quietCtaSecondaryClass =
  "inline-flex min-h-[40px] max-w-full items-center justify-center gap-1.5 rounded-full border border-transparent bg-transparent px-3 py-2 text-center font-body text-[10px] uppercase tracking-[0.18em] text-foreground/86 transition-all duration-300 ease-out shadow-[inset_0_-1px_0_hsl(var(--border)/0.22)] hover:border-border/60 hover:bg-background/30 hover:text-foreground hover:shadow-[0_8px_16px_hsl(var(--background)/0.12)] focus-visible:border-primary/24 focus-visible:bg-background/44 focus-visible:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/35 active:border-border/58 active:bg-background/38 sm:min-h-[42px] sm:px-3.5 sm:text-[11px] sm:tracking-[0.22em]";

export const quietCtaTertiaryClass =
  "inline-flex min-h-[36px] max-w-full items-center justify-center gap-1.5 rounded-full border border-transparent bg-transparent px-2.5 py-1.5 text-center font-body text-[10px] uppercase tracking-[0.18em] text-muted-foreground transition-all duration-300 ease-out shadow-[inset_0_-1px_0_hsl(var(--border)/0.18)] hover:border-border/48 hover:bg-background/30 hover:text-foreground hover:shadow-[0_6px_14px_hsl(var(--background)/0.10)] focus-visible:border-primary/22 focus-visible:bg-background/40 focus-visible:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/32 active:border-border/46 active:bg-background/36 sm:min-h-[38px] sm:px-3 sm:text-[11px] sm:tracking-[0.2em]";

export const quietSocialChipClass =
  "group inline-flex min-h-[40px] max-w-full items-center justify-center gap-2 rounded-full border border-primary/18 bg-primary/[0.03] px-3.5 py-2 font-body text-primary/92 transition-all duration-300 ease-out hover:border-primary/28 hover:bg-primary/[0.055] hover:shadow-[0_10px_18px_hsl(var(--primary)/0.08)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/28 active:border-primary/28 active:bg-primary/[0.055] sm:min-h-[42px] sm:px-4";

export const quietSocialHandleClass =
  "text-[11px] font-medium uppercase tracking-[0.12em] sm:text-xs md:text-[13px]";
