export const quietCtaPrimaryClass =
  "inline-flex min-h-[40px] max-w-full items-center justify-center gap-1.5 rounded-full border border-primary/12 bg-transparent px-3 py-2 text-center font-body text-[10px] uppercase tracking-[0.18em] text-primary/92 transition-all duration-300 ease-out shadow-[inset_0_-1px_0_hsl(var(--primary)/0.14)] hover:border-primary/22 hover:bg-primary/[0.035] hover:text-primary hover:shadow-[0_8px_16px_hsl(var(--primary)/0.08)] focus-visible:border-primary/26 focus-visible:bg-primary/[0.05] focus-visible:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/24 active:border-primary/24 active:bg-primary/[0.045] sm:min-h-[42px] sm:px-3.5 sm:text-[11px] sm:tracking-[0.22em]";

export const quietCtaSecondaryClass =
  "inline-flex min-h-[40px] max-w-full items-center justify-center gap-1.5 rounded-full border border-primary/10 bg-transparent px-3 py-2 text-center font-body text-[10px] uppercase tracking-[0.18em] text-primary/78 transition-all duration-300 ease-out shadow-[inset_0_-1px_0_hsl(var(--primary)/0.11)] hover:border-primary/18 hover:bg-primary/[0.028] hover:text-primary/96 hover:shadow-[0_8px_16px_hsl(var(--primary)/0.06)] focus-visible:border-primary/24 focus-visible:bg-primary/[0.045] focus-visible:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/22 active:border-primary/20 active:bg-primary/[0.04] sm:min-h-[42px] sm:px-3.5 sm:text-[11px] sm:tracking-[0.22em]";

export const quietCtaTertiaryClass =
  "inline-flex min-h-[36px] max-w-full items-center justify-center gap-1.5 rounded-full border border-primary/8 bg-transparent px-2.5 py-1.5 text-center font-body text-[10px] uppercase tracking-[0.18em] text-primary/68 transition-all duration-300 ease-out shadow-[inset_0_-1px_0_hsl(var(--primary)/0.09)] hover:border-primary/16 hover:bg-primary/[0.022] hover:text-primary/90 hover:shadow-[0_6px_14px_hsl(var(--primary)/0.05)] focus-visible:border-primary/20 focus-visible:bg-primary/[0.04] focus-visible:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/20 active:border-primary/18 active:bg-primary/[0.034] sm:min-h-[38px] sm:px-3 sm:text-[11px] sm:tracking-[0.2em]";

export const quietSocialChipClass =
  "group inline-flex min-h-[40px] max-w-full items-center justify-center gap-2 rounded-full border border-primary/12 bg-primary/[0.02] px-3.5 py-2 font-body text-primary/92 transition-all duration-300 ease-out hover:border-primary/22 hover:bg-primary/[0.042] hover:shadow-[0_10px_18px_hsl(var(--primary)/0.07)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/24 active:border-primary/22 active:bg-primary/[0.04] sm:min-h-[42px] sm:px-4";

export const quietSocialHandleClass =
  "text-[11px] font-medium uppercase tracking-[0.12em] sm:text-xs md:text-[13px]";
